import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Flex } from "@chakra-ui/react";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          {/* <Flex flexDirection={"column-reverse"}>
            <Header>{children}</Header>
          </Flex> */}
        </Providers>
      </body>
    </html>
  );
}
